sonar.projectKey=chirag127_oriz-packages-catalog-app
sonar.organization=chirag127
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/__tests__/**,**/node_modules/**,**/dist/**,**/.astro/**
